name: spgie
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - appnope=0.1.3
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - comm=0.1.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.9.2
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.5.1
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.0
  - packaging=23.1
  - pandas=2.1.1
  - parso=0.8.3
  - partd=1.4.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyg=2.4.0
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cluster=1.6.1
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tk=8.6.12
  - toolz=0.12.0
  - torchvision=0.14.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wcwidth=0.2.12
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
